# Generated by Django 4.2.20 on 2025-07-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelotrain',
            name='C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelotrain',
            name='kernel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelodataset',
            name='model_type',
            field=models.CharField(choices=[('CNN', 'Cnn'), ('LSTM', 'Lstm'), ('NAIVE_BAYES', 'Naive Bayes'), ('KMEANS', 'Kmeans'), ('SVM', 'Svm')], max_length=20),
        ),
    ]
